### ISSUE TITLE
IP type preference with fallback

### ISSUE THREAD

**Issue by cehoffman** [GoogleCloudPlatform/cloud-sql-go-connector#362]
## Feature Description
Similar to #244 but more opposite direction. With `cloud-sql-proxy` it is possible to set an order of preferred IP type to use and a fallback if that type is not available. For instance, we would like to default to using private IPs if the instance has one and fallback to public if no private IP exists.

## Alternatives Considered
Every CloudSQL instance we connect with needs to include information on the IP types it supports before registering the `database/sql` handler. 

## Additional Context
See #244 which does this for public IPs with fallback to private IP if no public.

**Comment by enocom** [comment]
Thanks for the feature request.

The recent addition of `WithAutomaticIPAddressSelection` was for backwards compatibility and for anyone who depended on the behavior of the v1 proxy. Otherwise, we've found non-deterministic IP address selection is a source of many surprises, support cases, bugs, etc., and so we generally discourage people from relying on the behavior and instead think specifically asking for public or private IP at runtime is better. So I'd prefer not to add any more options like this.

That said, there are possible solutions for people who maybe run in dev against a public IP and in prod against private IP. 

If you're running code in multiple environments where sometimes you have private IP and sometimes public IP, you can do something like this:

``` golang
var opts cloudsqlconn.Option
if os.Getenv("USE_PUBLIC_IP") != "" {
  opts = append(opts, cloudsqlconn.WithPublicIP()
} else {
  // default to private if public env var wasn't set
  opts = append(opts, cloudsqlconn.WithPrivateIP()
}
```

Would that help what you're trying to accomplish @cehoffman?

**Comment by enocom** [comment]
Another option here would be to extend the instance connection name and add support for query params as we have in the v2 proxy, e.g.,

``` 
myproject:us-central1:mydb?private-ip=true
```

This is really a variation of the above where the DSN would live in an environment variable and would allow a user to configure options in one place, rather than with cloudsqlconn.Option types.

**Comment by enocom** [comment]
Going to close this as stale. Fee free to re-open if you’d like to explore options further.
