### ISSUE TITLE
Does sslmode param make any difference ?

### ISSUE THREAD

**Issue by Bakhtiyar-Garashov** [GoogleCloudPlatform/cloud-sql-go-connector#889]
### Question

Hi there! I am working on a project which uses cloud-sql-go-connector. As far as I have read the connector itself manages the SSL encryption implicitly. My question is does `sslmode={value}` make any difference in that case (considering the Cloud SQL Postgres instance have SSL enabled with `ENCRYPTED_ONLY` option) ? As far as I have seen all examples set the `sslmode=disable`

Thanks in advance.

**Comment by jackwotherspoon** [comment]
Hi @Bakhtiyar-Garashov let me see if I can help you here.

```go
// Configure the driver to connect to the database
dsn := "user=myuser password=mypass dbname=mydb sslmode=disable"
config, err := pgxpool.ParseConfig(dsn)
```
The reason behind why we showcase `sslmode=disable` in our samples is so that the underlying database driver does not try to configure the SSL (otherwise the default is `sslmode=prefer`). 

In the case above we don't want the `pgx` library to configure the SSL as like you said the Go Connector will always create an SSL/TLS connection itself. We do not want the database driver to do any wasted cycles, so setting it to disable will allow the Go Connector to always handle the secure connection itself:

https://github.com/GoogleCloudPlatform/cloud-sql-go-connector/blob/5061c61092c3fa92175ca8502a365e6e82993b6e/internal/cloudsql/instance.go#L238-L269

Let me know if this helps clear things up, happy to explain in further detail if need be.

**Comment by jackwotherspoon** [comment]
@Bakhtiyar-Garashov 

> What if i set SSL mode to "ENCRYPTED_ONLY" in Cloud SQL instance config and set `sslmode=disable` ? Bit confused on that part.

This will still work, and we actually recommend setting `ENCRYPTED_ONLY` or even `TRUSTED_CLIENT_CERTIFICATE_REQUIRED` when creating a Cloud SQL instance, both will work since the Go Connector creates mTLS connections using a generated client cert. Again `sslmode=disable` is just so that the `pgx` library does not create the SSL connection, the Go Connector will still always create and establish an SSL connection to your database.

> Lastly, when I check pg_stats_ssl I see that all connections are having SSL False.

Correct. All Go Connector connections use SSL/TLS to connect your application to the Proxy server (port 3307) sitting alongside the database on the Cloud SQL instance. At which point the SSL is terminated at the Proxy server and a local unix connection is used between the Proxy server and the database.

![image](https://github.com/user-attachments/assets/090bdbb3-77f0-459e-a5c4-cf5683a9e2c9)

**Comment by Bakhtiyar-Garashov** [comment]
Thanks a lot! Really helpful.

**Comment by jackwotherspoon** [comment]
> Thanks a lot! Really helpful.

Glad I could help, thanks for the question. It is a very good one and one I'm sure more people have wondered. 

I will work on creating a detailed diagram (better version of the one above) and have it added to our README and Google Cloud docs 👍
